using System;
using System.Collections.Generic;
using System.Text;

namespace Syllabore
{
    /// <summary>
    /// Transforms names generated by an <see cref="INameGenerator"/>.
    /// </summary>
    public interface INameTransformer
    {
        /// <summary>
        /// Applies one or more transforms on the specified <see cref="Name"/>
        /// and returns a new <see cref="Name"/> as the result.
        /// </summary>
        Name Apply(Name sourceName);
    }
}
