using System;
using System.Collections.Generic;
using System.Text;

namespace Syllabore
{
    /// <summary>
    /// Transforms names generated by a name generator.
    /// </summary>
    public interface INameTransformer
    {
        /// <summary>
        /// Applies changes to the specified <see cref="Name"/>
        /// and returns a new <see cref="Name"/> as the result.
        /// </summary>
        Name Apply(Name sourceName);
    }
}
